# fly.toml app configuration file generated for high-speed-connection on 2026-09-08T12:14:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'high-speed-connection'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[mounts]
  source = "hsc_data"
  destination = "/data"

[deploy]
  strategy = 'bluegreen'
